# https://pr-agent-docs.codium.ai/
# https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml

[config]
response_language = "ja-JP"
enable_auto_approval = true
auto_approve_for_low_review_effort = 3
auto_approve_for_no_suggestions = true

[pr_description]
generate_ai_title = true
final_update_message = true
extra_instructions="""\
Emphasize the following:
- Please use Japanese for everything.
- Titles should have a prefix following the commitlint pattern, such as feat:, chore:, test:, fix:, docs:, style:, refactor:, perf:, etc.
"""

[pr_reviewer]
require_score_review = true
require_tests_review = false
require_estimate_effort_to_review = true
require_can_be_split_review = true
enable_review_labels_effort = false
extra_instructions="""\
Emphasize the following:
- Please use Japanese for everything.
"""

[pr_code_suggestions]
focus_only_on_problems = true
commitable_code_suggestions = true
demand_code_suggestions_self_review = true
extra_instructions="""\
Emphasize the following:
- Please use Japanese for everything.
"""

